# Generated by Django 4.2.11 on 2024-05-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_pagemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("url", models.CharField(max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="users.pagemodel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language"], name="users_pageu_languag_f6800e_idx"
                    )
                ],
                "unique_together": {("page", "language")},
            },
        ),
    ]
